import { Control, HeliParams, HeliState, hoverControl, step } from '../physics/heli';
import { HoverController } from './autopilot';

/**
 * A reference trajectory: a feasible state sequence with the controls that
 * produce it (states[t+1] = step(states[t], controls[t], dt)). Because every
 * reference here is generated by rolling the *true* model forward, it is exactly
 * dynamically feasible — so the tracking LQR only has to reject disturbances, not
 * fight an impossible target. (Phase 3 will instead *learn* such references from
 * demonstrations, which is the harder, more general problem.)
 */
export interface Reference {
  name: string;
  states: HeliState[]; // length N+1
  controls: Control[]; // length N
  dt: number;
}

const smoothstep = (a: number, b: number, x: number): number => {
  const t = Math.min(1, Math.max(0, (x - a) / (b - a)));
  return t * t * (3 - 2 * t);
};

/** Roll out an open-loop feedforward control schedule. */
const rolloutFeedforward = (
  params: HeliParams,
  start: HeliState,
  dt: number,
  steps: number,
  uff: (t: number, s: HeliState) => Control,
): { states: HeliState[]; controls: Control[] } => {
  const states = [start];
  const controls: Control[] = [];
  for (let k = 0; k < steps; k++) {
    const u = uff(k * dt, states[k]);
    controls.push(u);
    states.push(step(params, states[k], u, dt));
  }
  return { states, controls };
};

/**
 * Roll out the hover LQR while chasing a moving setpoint. Produces a smooth,
 * altitude-holding, feasible reference for gentle (non-inverted) maneuvers where
 * the hover linearization stays valid.
 */
const rolloutTracking = (
  params: HeliParams,
  start: HeliState,
  dt: number,
  steps: number,
  setpoint: (t: number) => { pos: { x: number; y: number; z: number }; yaw: number },
): { states: HeliState[]; controls: Control[] } => {
  const ctrl = new HoverController(params, dt);
  const states = [start];
  const controls: Control[] = [];
  for (let k = 0; k < steps; k++) {
    const sp = setpoint(k * dt);
    ctrl.setSetpoint(sp.pos, sp.yaw);
    const u = ctrl.control(states[k]);
    controls.push(u);
    states.push(step(params, states[k], u, dt));
  }
  return { states, controls };
};

export type ManeuverId = 'forward' | 'square' | 'flip' | 'loop';

export const MANEUVER_IDS: ManeuverId[] = ['forward', 'square', 'flip', 'loop'];

/** Build a named maneuver reference starting from `start`. */
export const buildManeuver = (
  id: ManeuverId,
  params: HeliParams,
  start: HeliState,
  dt: number,
): Reference => {
  const z = start.position.z;
  const x0 = start.position.x;
  const y0 = start.position.y;
  const hover = hoverControl(params);

  switch (id) {
    case 'forward': {
      // Accelerate forward 14 m and stop, holding altitude.
      const steps = Math.round(8 / dt);
      const { states, controls } = rolloutTracking(params, start, dt, steps, (t) => ({
        pos: { x: x0 + 14 * smoothstep(0.5, 5.5, t), y: y0, z },
        yaw: 0,
      }));
      return { name: 'Forward flight', states, controls, dt };
    }
    case 'square': {
      // Trace a 10 m box at constant altitude.
      const side = 10;
      const leg = 3; // s per leg
      const steps = Math.round(4 * leg / dt);
      const corners = [
        [x0, y0],
        [x0 + side, y0],
        [x0 + side, y0 + side],
        [x0, y0 + side],
        [x0, y0],
      ];
      const { states, controls } = rolloutTracking(params, start, dt, steps, (t) => {
        const f = t / leg;
        const i = Math.min(corners.length - 2, Math.floor(f));
        const u = smoothstep(0, 1, f - i);
        return {
          pos: {
            x: corners[i][0] + (corners[i + 1][0] - corners[i][0]) * u,
            y: corners[i][1] + (corners[i + 1][1] - corners[i][1]) * u,
            z,
          },
          yaw: 0,
        };
      });
      return { name: 'Square pattern', states, controls, dt };
    }
    case 'flip': {
      // In-place pitch flip: a brief climb, then a sustained nose-up rotation
      // through 360° while *pumping the collective* with the rotation phase
      // (push up when upright, reverse when inverted) to limit altitude loss —
      // the trick real flip pilots use. Still a feasible rollout, and still
      // imperfect (it drifts), which is exactly what Phase 3's learning removes.
      const climb = 0.5;
      const spin = 1.55; // ≈ 360° at the pitch-rate steady state
      const steps = Math.round((climb + spin + 1.2) / dt);
      const { states, controls } = rolloutFeedforward(params, start, dt, steps, (t) => {
        if (t < climb) return { ...hover, u4: 1 };
        if (t < climb + spin) {
          const phase = (t - climb) / spin; // 0..1 over the 360°
          return { u1: 0, u2: 1, u3: 0, u4: 0.5 * Math.cos(2 * Math.PI * phase) };
        }
        return hover;
      });
      return { name: 'In-place flip', states, controls, dt };
    }
    case 'loop': {
      // Vertical loop: build forward speed, then a sustained nose-up arc.
      const accel = 1.0;
      const arc = 3.2;
      const steps = Math.round((accel + arc + 1.0) / dt);
      const { states, controls } = rolloutFeedforward(params, start, dt, steps, (t) => {
        if (t < accel) return { u1: 0, u2: -0.35, u3: 0, u4: hover.u4 + 0.1 };
        if (t < accel + arc) return { u1: 0, u2: 0.6, u3: 0, u4: 0.6 };
        return hover;
      });
      return { name: 'Loop', states, controls, dt };
    }
  }
};
